# -*- coding: utf-8 -*-
"""Introdução a Análise Exploratória de Dados (AED) utilizando a biblioteca Pandas do Python.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nNVtNVzHyuui4XMxTIkFrpWHcRbwgxNg

# **Introdução à Análise Exploratória de Dados utilizando a biblioteca Pandas**
---

##**01. Ferramentas e bibliotecas para análise exploratória de dados**

* [Google Colab ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjRgtCVrqDqAhUUKLkGHc6jDnQQFjAAegQIARAC&url=https%3A%2F%2Fcolab.research.google.com%2F&usg=AOvVaw3A5aPK2kLFzKOzb6sOckVw): serviço de nuvem gratuito hospedado pelo Google para incentivar a pesquisa de Aprendizado de Máquina e Inteligência Artificial;
* Bibliotecas **Python**: **pandas**, **matplotlib**

### Referências sobre a biblioteca **pandas** e **matplotlib**:

* [pandas](https://pandas.pydata.org/docs/getting_started/index.html#getting-started) é uma biblioteca para análise de dados em Python, de código aberto, licenciada por BSD, utiliza o conceito de dataframes que funcionam como uma matriz de dados, formada por linhas e colunas.

* [pandas](https://pandas.pydata.org/) pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

* Documentação da biblioteca [matplotlib](https://pandas.pydata.org/).

* Exemplos de uso da biblioteca [pandas](https://minerandodados.com.br/analise-de-dados-com-python-usando-pandas/).

* Documentação da biblioteca [matplotlib](https://matplotlib.org/).

* Notebook introdução aos dataframes em pandas [Dataframes em Pandas](https://colab.research.google.com/drive/1-b-e_xmhWVljGEmb7VGzSHRjmHcKIVAK?usp=sharing).
"""

# importar a biblioteca pandas
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import matplotlib.dates as mdates

"""## **02. O que é análise Exploratória de Dados (AED)**
A estatística **descritiva** é a etapa **inicial** da análise utilizada para **descrever** e **resumir** os dados. A disponibilidade de uma **grande quantidade de dados** e de métodos **computacionais** muito eficientes revigorou está área da **estatística**.
 [Estatística Descritiva - IME -(Davila, Victor H L)](https://www.ime.unicamp.br/~hlachos/estdescr1.pdf).

A **Análise Exploratória de Dados** começa **antes** da aplicação de **qualquer** técnica **estatística**. É necessário **conhecer** os dados que serão analisados, se eles estão no **formato** correto, se possuem algum **relacionamento**, o signficato **exato** de cada **coluna** que será **utilizada** da tabela de dados que será analisada.

**Após** a coleta e a digitação de dados em um banco de dados apropriado, o próximo passo é a **análise descritiva**. Esta etapa é fundamental, pois uma análise descritiva detalhada permite ao pesquisador familiarizar-se com os dados, organizá-los e sintetizá-los de forma a obter as informações necessárias do
**conjunto** de dados para responder as questões que estão sendo estudadas.

A Análise Exploratória de Dados vai **além** do uso **descritivo** da estatística, pois procura olhar de forma mais **profunda os dados**, sem **resumir** muito a **quantidade de informações**. utilizando uma diversidade de ferramentas computacionais para analisar os dados.

[Análise Exploratória de Dados](http://www.each.usp.br/lauretto/SIN5008_2011/aula01/aula1)

##**03. Tratamento dos dados**

* A organização dos dados coletados é **fundamental** para que não hajam **erros** de processamento e **perda** de informações;

* A **apresentação** dos dados **depende** do tipo de variável e daquilo que se quer **mostrar**;

**Convenções para os dados de entrada**

* Os dados devem estar no formato de **matriz** (linha x coluna);
* Cada linha da matriz corresponde a **uma** unidade experimental (**elemento** da **população** ou **amostra** no qual observamos as variáveis/**colunas** da tabela);
* Cada **coluna** da matriz corresponde a uma **variável**;

**Dados brutos**

* Quando fazemos uma coleta de dados, e armazenamos de forma correta, temos em mãos o que se chama de **dados brutos**, pois consiste das observações **“puras”**, sem **nenhum** tipo de processamento ou resumo;

* Uma análise de dados **sempre** deve começar com uma planilha de dados **brutos**, pois será a partir deles que iremos resumir e visualizar as informações de **interesse**.

**Gráficos e Resumos Numéricos**

Os gráficos constituem uma das formas mais eficientes de apresentação de dados. Um gráfico é, essencialmente, uma figura constituída a partir de uma tabela, pois é quase sempre possível localizar um dado tabulado num gráfico;

Enquanto as tabelas fornecem uma idéia mais precisa e possibilitam um tratamento mais rigoroso aos dados, os gráficos são mais indicados para dar uma visão mais rápida de como estão dispostas as variáveis. A qualidade na representação gráfica deve ser pautada na clareza, simplicidade e autoexplicação. As técnicas gráficas desempenham um papel fundamental na AED.

![](https://github.com/paulosrl/imagens/blob/master/tipografico.png?raw=true)

Fonte: http://www.each.usp.br/lauretto/SIN5008_2011/aula01/aula1

Adotaremos dois tipos de gráfico neste documento, para analisar as primeiras análises aos dados numéricos, ambos os gráficos só se aplicam a valores numéricos (quantitativos discretos ou contínuos). Os gráficos são os histogramas e os box-plots.

## **04. Distribuição Estatística dos dados**

**Análise univariada**

A análise univariada consiste em analisar **cada** variável da amostra:
* Classificar o seu tipo: **qualitativa** (nominal ou ordinal) ou **quantitativa** (discreta ou contínua);

* Obter tabelas, gráficos e/ou medidas que **resumam** a variável;

* A partir destes resultados pode-se montar um **resumo geral** dos dados.

**Variáveis**

Quando fazemos uma amostragem, coletamos não apenas a informação sobre a característica de interesse, mas diversas outras informações que auxiliarão no entendimento desta característica.

**Cada** uma das **características** da população amostrada, como peso, altura, sexo ou idade, é denominada de uma **variável**.

As variáveis podem assumir diferentes valores, que basicamente podem ser **separados** em

* **Quantitativos** ou numéricos
* **Qualitativos** ou não numéricos, ou categóricos

![texto alternativo](http://leg.ufpr.br/~fernandomayer/aulas/ce001e-2016-2/img/classificacao_variaveis.png)

**Classificação de variáveis**

**As variáveis quantitativas ou numéricas podem ser**

* **Discretas**: assumem apenas valores inteiros. Ex.: número de irmãos, número de passageiros;
* **Contínuas**: assume qualquer valor no intervalo dos números reais. Ex.: peso, altura.

Fonte: http://leg.ufpr.br/~fernandomayer/aulas/ce001e-2016-2/02_Analise_Exploratoria_de_Dados.html

**As variáveis qualitativas ou categóricas podem ser**

* **Nominais**: quando as categorias não possuem uma ordem natural. Ex.: nomes, cores, sexo;
* **Ordinais**: quando as categorias podem ser ordenadas. Ex.: tamanho (pequeno, médio, grande), classe social (baixa, média, alta), grau de instrução (básico, médio, graduação, pós-graduação).

### **Medidas de resumo estatístico dos dados**

Uma maneira de se resumir os dados de uma variável quantitativa é utilizando medidas descritivas. Estas medidas, se calculadas a partir de dados populacionais, são denominadas parâmetros e se calculadas
a partir de dados amostrais são denominadas estimadores ou estatísticas.

As medidas descritivas auxiliam a análise do comportamento dos dados. Tais dados são provenientes de uma população ou de uma amostra.

Essas medidas descritivas são também chamadas de medida de tendência central. As medidas de tendência central são assim denominadas por indicarem um **ponto** em torno do qual se **concentram** os dados. Este ponto **tende** a ser o centro da **distribuição** dos dados.

Neste artigo iremos nos concentrar nas seguintes medidas: **média, mediana e desvio padrão**, estas medidas resumem os dados em torno de um ponto **central**.

####**Média**
A média aritmética é considerada uma medida de tendência central e é muito utilizada no cotidiano. Surge do resultado da divisão do somatório dos números dados pela quantidade de números somados.

Esse tipo de cálculo é muito utilizado em campeonatos de futebol, no intuito de determinar a média de gols da rodada; nas escolas, para o cálculo da média final dos alunos; nas pesquisas estatísticas, pois a média dos resultados determina o direcionamento das ideias expressas pelas pessoas pesquisadas etc.

No exemplo a seguir veremos como calcular a **média** da séria **(0,1,0,1,1,1,0,0,0,15,11,10,9)**.
"""

# calcular a média da séria (0,1,0,1,1,1,0,0,0,15,11,10,9)
pd.Series([0,1,0,1,1,1,0,0,0,15,11,10,9]).mean()

"""####**Mediana**
O termo “mediana” refere-se a “meio”. Dado um conjunto de informações numéricas, o valor central corresponde à mediana desse conjunto. Dessa forma, é importante que esses valores sejam colocados em ordem, seja crescente ou decrescente. Se houver uma quantidade ímpar de valores numéricos, a mediana será o valor central do conjunto numérico. Se a quantidade de valores for um número par, devemos fazer uma média aritmética dos dois números centrais, e esse resultado será o valor da mediana.

No exemplo a seguir veremos como calcular a **mediana** da séria **(0,1,0,1,1,1,0,0,0,15,11,10,9)**.

https://pt.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/measuring-center-quantitative/e/calculating-the-median
"""

# calcular a mediana
pd.Series([0,1,0,1,1,1,0,0,0,15,11,10,9]).median()

"""####**Média *X* Mediana**

É sempre necessário observar ambas as medidas, cada medida depende diretamente de como estão distribuídos os dados. No Exemplo a seguir iremo utilizar dois exemplos de conjuntos de dados.

Conjunto1 = [1,2,3,4,5]

Conjunto2 = [1,2,3,4,50]

A seguir iremos aplicar o cálculo da média e da mediana para ambos os conjuntos.
"""

# conjunto de dados
Conjunto1 = [1,2,3,4,5]
Conjunto2 = [1,2,3,4,50]

#média para o primeiro conjunto de dados
pd.Series(Conjunto1).mean()

#mediana para o primeiro conjunto de dados
pd.Series(Conjunto1).median()

#média para o segundo conjunto de dados
pd.Series(Conjunto2).mean()

#mediana para o segundo conjunto de dados
pd.Series(Conjunto2).median()

"""As duas amostras se diferenciam apenas pelo último valor, ou seja, foi inserido um valor discrepante (outlier), um valor que é muito diferente dos demais, esses valores acabam por contaminar a **MÉDIA**.

O outlier "puxa" os valores para cima, distorcendo completamente a média. Quando for escolher uma medida de tendência central, é importante analisar os dados, se a média e a media forem próximas é possível que não existam valores discrepantes na amostra.

Se **não houverem valores discrepantes** na amostra a melhor escolha é a **média**, mas ainda assim é imporante calcular a mediana e analisar os dois valores.

Caso **existam valores discrepantes** o melhor usar a **mediana**.

É importante entender os valores discrepantes, se eles realmente representam um comportamento dos dados, ou se o valor é um erro amostral, caso seja um erro, esse valor deverá ser retirado da amostra e refeito os cálculos da média e mediana, analisando novamente os dois valores.

#### **Desvio Padrão**

Desvio padrão é uma medida de dispersão em torno da média populacional de uma variável.

$$SD = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \overline{x}) ^ 2}$$

Falando simplificadamente, um número alto do desvio padrão indica que os dados estão bem espelhados em relação à sua média. Já um desvio padrão baixo mostra que os valores estão mais agrupados, mais "juntos".

Por exemplo, na figura abaixo temos um exemplo de valores altos e baixos para o desvio padrão. Em vermelho os dados estão mais próximos à sua média (**desvio baixo**), e em azul estão bem mais espalhados (**desvio alto**).

<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Comparison_standard_deviations.svg/450px-Comparison_standard_deviations.svg.png" height="450px">
</center>

Este exemplo mostra duas populações com médias iguais e desvio padrões diferentes. A população em veremlho tem média 100 e desvio padrão igual a 10, a população em azul, tem média 100 e desvio padrão de 50.

Para quem não está acostumado com gráficos de distribuições, um exemplo que funciona muito bem é o do tiro ao alvo.

Olhe na figura abaixo como os tiros estão localizados em cada uma das situações. Identifique mentalmente quais tem maior ou menor dispersão, ou seja, desvio padrão.

<center><img src="https://raw.githubusercontent.com/carlosfab/dsnp2/master/img/precisao_exatidao.jpg" height="450px"></center>

O conceito que eu quero que você se atente é o achatamento da curva. Como os valores se "aglomeram" em torno da média ou se dispersam em torno dela. Veja também mais essa outra figura abaixo, colocando as distribuições lado a lado.

<center><img src="https://raw.githubusercontent.com/carlosfab/dsnp2/master/img/precisao_vs_exatidao2.jpg" height="400px"></center>

Para calcular o desvio padrão de qualquer coluna, basta executar o método `std()` para a variável.

* Curso Data Science na Prática 2.0 by [sigmoidal.ai](https://sigmoidal.ai)*

É uma medida de separação do conjunto de dados, que mede o quão diferente os valores de um conjunto de dados se diferem entre si, conhecido também como desvio padrão populacional.

Na área estatística, o desvio de padrão é chamado especificamente de desvio de padrão amostral. Um baixo desvio indica que os dados estão próximos da média ou do valor esperado. Já um alto desvio padrão, indica que os dados estão espalhados por uma ampla gama de valores.

**Conclusões**

* O **desvio padrão** é um valor positivo, indica a **distância** entre os valores medidos e a **média**;
* O **desvio padrão** junto a média aritmética, ajudam a **entender** o quão "confiável" é um valor;
* Um desvio padrão **grande** significa que os valores amostrais estão **distantes** da média;
* Um desvio padrão **pequeno** (próximo de zero) indica que eles estão **condensados próximos** da média;
* Quanto **menor** o desvio padrão, mais **homogênea** é a amostra;
* Quando o desvio padrão é **igual a zero** é porque ele é **igual** a média.

No exemplo a seguir veremos como calcular o **desvio padrão** da séria **(0,1,0,1,1,1,0,0,0,15,11,10,9)**.
"""

# desvio padrão
pd.Series([0,1,0,1,1,1,0,0,0,15,11,10,9]).std()

"""**Referências de apoio:** 

* [Exemplo de média, mediana e moda](https://pt.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/measuring-center-quantitative/v/mean-median-and-mode)
* [Medidas de dispersão: intervalo, variância e desvio-padrão](https://pt.khanacademy.org/math/probability/data-distributions-a1/summarizing-spread-distributions/v/range-variance-and-standard-deviation-as-measures-of-dispersion)
* [Desvio-padrão amostral e viés](https://pt.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/measuring-spread-quantitative/v/sample-standard-deviation-and-bias)

##**05. Gráficos para o resumo estatístico dos dados**

Neste estudo iremos nos concentar em dois gráficos para mostrar como está a distribuição dos dados (resumo estatístico), são eles os **Boxplots** e os **Histogramas**.

###**Boxplots**

O **Boxplot** (gráfico de caixa) é um gráfico utilizado para representar dados quantitativos sendo conveniente para revelar medidas de tendência central, dispersão, distribuição dos dados e a presença de outliers (valores discrepantes).

O boxplot é formado pelo **primeiro** e **terceiro** quartil e pela **mediana**. As hastes inferiores e superiores se estendem, respectivamente, do quartil **inferior** até o **menor valor** não inferior ao **limite inferior** e do quartil **superior** até o **maior valor** não superior ao **limite superior**. 

**VARIAÇÃO INTERQUARTIL = Q3-Q1**

Onde **Q3** (terceiro quartil) representa **75%** dos dados e **Q1** (primeiro quartil) representa **25%** dos dados
# IQR = Q3 - Q1

O **desvio padrão** e a **variância** dependem da **média**, e por isso ão **afetados** por valores **extremos**. A **variação interquartil** (IQR em inglês), é uma medida de dispersão baseada na **mediana**, funciona de maneira bem mais **eficiente** na presença de **outliers**, ou seja, é pouco afetada pelo outliers.

Os limites são **calculados** da seguinte forma:

**Limite** **inferior (mínimo)**: $ Q_1-1,5 * (Q_3-Q_1)\ $

**Limite** **superior (máximo)**: $ Q_3+1,5 * (Q_3-Q_1)\ $

Os pontos fora destes limites são considerados valores **discrepantes (outliers)** e são denotados por asterisco (*). A Figura  a seguir apresenta um exemplo do formato de um boxplot.

<center><img src="https://raw.githubusercontent.com/paulosrl/imagens/master/boxplot-1-1024x664.png" height="450px"></center>

Use o Boxplot para avaliar e comparar o formato, tendência central e variabilidade de distribuições de amostra, e para procurar por outliers. Um boxplot funciona melhor quando o tamanho amostral é de pelo menos 20. Por padrão, um boxplot demonstra a mediana, amplitude interquartil, amplitude e outliers para cada grupo.

Fonte: https://support.minitab.com/pt-br/minitab/18/help-and-how-to/graphs/how-to/boxplot/before-you-start/overview/

**Estudo de caso: Aplicando Boxplots em uma coluna de dados**
Nos exemplos a seguir será utilizado um banco de dados que armazena a expectativa de vida, dos Brasileiros, Bolivianos e Norte Americanos (em anos), no período de 1960 a 2013. Os três gráficos a seguir (boxplots) mostram como está a distribuição dos dados para os três países.
"""

#Brasil
vExpectativaBrasil = [54.69214634,55.16963415,55.63309756,56.08,56.51029268,56.92387805,57.32319512,57.7117561,58.09460976,58.47529268,58.85697561,59.24436585,59.63753659,60.0355122,60.43819512,60.83978049,61.23543902,61.62039024,61.9925122,62.35382927,62.70604878,63.05646341,63.4104878,63.77392683,64.14792683,64.53253659,64.92614634,65.32353659,65.72207317,66.11921951,66.515,66.90997561,67.30573171,67.70080488,68.09465854,68.48273171,68.86195122,69.23121951,69.58746341,69.92968293,70.25739024,70.56965854,70.86956098,71.15960976,71.44178049,71.71853659,71.99178049,72.26290244,72.53387805,72.80417073,73.07531707,73.34736585,73.61787805,73.88595122]
fig, ax = plt.subplots(figsize=(10,10))
ax.set_title('Distribuição da Média da Expectativa de vida - Brasil (1960 a 2013)')
ax.boxplot(vExpectativaBrasil);

#Bolívia
vExpectativaVidaBolivia = [42.66812195,42.97687805,43.28914634,43.60341463,43.92117073,44.23641463,44.54312195,44.84078049,45.13641463,45.43956098,45.76626829,46.13563415,46.56017073,47.05041463,47.60787805,48.23297561,48.92019512,49.65292683,50.41363415,51.18980488,51.96843902,52.74312195,53.50836585,54.26021951,54.98965854,55.69212195,56.36504878,57.01036585,57.6295122,58.21943902,58.77858537,59.30241463,59.79297561,60.25178049,60.68290244,61.09087805,61.48029268,61.85721951,62.22621951,62.59182927,62.95460976,63.31553659,63.67160976,64.02026829,64.3635122,64.70078049,65.03309756,65.36190244,65.68570732,66.00546341,66.31970732,66.62692683,66.92663415,67.21736585]
fig, ax = plt.subplots(figsize=(10,10))
ax.set_title('Distribuição da Média da Expectativa de vida - Bolívia (1960 a 2013)')
ax.boxplot(vExpectativaVidaBolivia);

#EUA
vExpectativaVidaEUA = [69.77073171,70.27073171,70.1195122,69.91707317,70.16585366,70.21463415,70.21219512,70.56097561,69.95121951,70.50731707,70.80731707,71.10731707,71.15609756,71.35609756,71.95609756,72.60487805,72.85609756,73.25609756,73.35609756,73.80487805,73.65853659,74.00731707,74.36097561,74.46341463,74.56341463,74.56341463,74.61463415,74.76585366,74.76585366,75.01707317,75.21463415,75.36585366,75.64219512,75.4195122,75.57439024,75.62195122,75.99658537,76.42926829,76.5804878,76.58292683,76.63658537,76.73658537,76.83658537,76.98780488,77.33902439,77.33902439,77.58780488,77.83902439,77.93902439,78.0902439,78.54146341,78.64146341,78.74146341,78.84146341]
fig, ax = plt.subplots(figsize=(10,10))
ax.set_title('Distribuição da Média da Expectativa de vida - EUA (1960 a 2013)')
ax.boxplot(vExpectativaVidaEUA);

"""**Estudo de caso: Boxplots comparando três colunas de dados (países)**

No exemplo a seguir foi utilizado o mesmo banco de dados do exemplo anterior, porém os histogramas foram plotados no mesmo gráfico, desta forma torna-se a mais fácil comparar a coluna expectativa de vida, pois será possível analisar os conjuntos de dados lado a lado para os três países.
"""

#dados por país
vExpectativaVidaBrasil = [54.69214634,55.16963415,55.63309756,56.08,56.51029268,56.92387805,57.32319512,57.7117561,58.09460976,58.47529268,58.85697561,59.24436585,59.63753659,60.0355122,60.43819512,60.83978049,61.23543902,61.62039024,61.9925122,62.35382927,62.70604878,63.05646341,63.4104878,63.77392683,64.14792683,64.53253659,64.92614634,65.32353659,65.72207317,66.11921951,66.515,66.90997561,67.30573171,67.70080488,68.09465854,68.48273171,68.86195122,69.23121951,69.58746341,69.92968293,70.25739024,70.56965854,70.86956098,71.15960976,71.44178049,71.71853659,71.99178049,72.26290244,72.53387805,72.80417073,73.07531707,73.34736585,73.61787805,73.88595122]
vExpectativaVidaBolivia = [42.66812195,42.97687805,43.28914634,43.60341463,43.92117073,44.23641463,44.54312195,44.84078049,45.13641463,45.43956098,45.76626829,46.13563415,46.56017073,47.05041463,47.60787805,48.23297561,48.92019512,49.65292683,50.41363415,51.18980488,51.96843902,52.74312195,53.50836585,54.26021951,54.98965854,55.69212195,56.36504878,57.01036585,57.6295122,58.21943902,58.77858537,59.30241463,59.79297561,60.25178049,60.68290244,61.09087805,61.48029268,61.85721951,62.22621951,62.59182927,62.95460976,63.31553659,63.67160976,64.02026829,64.3635122,64.70078049,65.03309756,65.36190244,65.68570732,66.00546341,66.31970732,66.62692683,66.92663415,67.21736585]
vExpectativaVidaEUA = [69.77073171,70.27073171,70.1195122,69.91707317,70.16585366,70.21463415,70.21219512,70.56097561,69.95121951,70.50731707,70.80731707,71.10731707,71.15609756,71.35609756,71.95609756,72.60487805,72.85609756,73.25609756,73.35609756,73.80487805,73.65853659,74.00731707,74.36097561,74.46341463,74.56341463,74.56341463,74.61463415,74.76585366,74.76585366,75.01707317,75.21463415,75.36585366,75.64219512,75.4195122,75.57439024,75.62195122,75.99658537,76.42926829,76.5804878,76.58292683,76.63658537,76.73658537,76.83658537,76.98780488,77.33902439,77.33902439,77.58780488,77.83902439,77.93902439,78.0902439,78.54146341,78.64146341,78.74146341,78.84146341]
fig, ax = plt.subplots(figsize=(18,12))
fig.set_facecolor("white") # cor de fundo

# juntar os dados em um dataset de registros
dados = {'Brasil': vExpectativaVidaBrasil, 'Bolivia': vExpectativaVidaBolivia,'EUA':vExpectativaVidaEUA}
df = pd.DataFrame(data=dados)
boxplot = df.boxplot(column=['Brasil','Bolivia','EUA'],grid=True)

"""### **Histogramas**

Um **histograma** é uma visualização gráfica de dados usando barras de diferentes alturas. Em um histograma, cada barra **agrupa** números em intervalos. As barras mais **altas** mostram que **mais dados** estão nesse intervalo. Um histograma exibe a forma e distribuição de dados amostrais discretos ou contínuos. ([Kanacademy](https://pt.khanacademy.org/math/ap-statistics/quantitative-data-ap/histograms-stem-leaf/v/histograms-intro))

Em resumo, o histograma mostra a distribuição das frequencias de um conjunto de dados quantitavivos contínuos ou discretos.

O [histograma](https://www.fm2s.com.br/histograma/) permite obter as seguintes informações

* **Centralidade**: qual é o centro de distribuição? Onde é esperado que esteja a maioria das observações?
* **Amplitude**: a distribuição normalmente contém observações entre quais valores? Qual é o ponto de máximo e o ponto de mínimo?
* **Simetria**: será que devemos esperar a mesma frequência de pontos com valor alto e com valor baixo? Será que o processo é simétrico ou valores mais altos são mais raros?

**Exemplo**:

Para estudar o comportamento das vendas, um administrador coleta informações sobre o número de itens vendidos nos últimos 30 dias e constrói um histograma com o auxílio do Minitab. Com esse gráfico, ele percebeu que suas vendas variavam entre **28 e 52 unidades** e na maioria dos dias ele vendia em torno de 40 unidades.


![texto alternativo](https://d1lc5plzz0mq74.cloudfront.net/wp-content/uploads/2015/08/21202945/ED_1.png)

**Cuidados ao elaborar um Histograma**

Um ponto **negativo** do histograma, quando falamos de análise de dados, é que ele é uma medida **estática**, ou seja, **não leva o tempo em consideração**. Por exemplo, eu não sei se todos os dias bons aconteceram na mesma época ou se eles estão dispersos aleatoriamente no processo.

Muitas vezes, ter essa informação sobre o período é crucial. Imagine que todos os dias bons aconteceram em uma semana, na qual o administrador estava com uma campanha de marketing em andamento. Ele poderia dizer, com certeza, que a campanha dele foi boa! Da mesma maneira, se todo os dias ruins também tivessem acontecido em uma semana mais fria, ele também entenderia melhor o que impacta nas vendas dele.

Ao fazer análises como essa, olhando como os dados se comportam ao longo do tempo, podemos procurar por causas comuns e causas especiais de variação.

Fonte: https://www.fm2s.com.br/histograma/

**Considerações sobre os dados com uso de Histograma**

Para o gráfico representar seus dados de forma mais eficaz, considere as seguintes diretrizes.

**O tamanho amostral deve ser de aproximadamente maior ou igual a 20 unidades**;

Se o tamanho de amostra for muito pequeno, cada barra no histograma pode não conter pontos de dados suficientes para demonstrar precisamente a distribuição dos dados. 

Se o tamanho amostral for menor do que 20, considere usar um gráfico de valor individual.

* Os dados de amostra devem ser selecionados **aleatoriamente**;
* Amostras aleatórias são usadas para fazer generalizações ou inferências, sobre uma população. Se os dados não foram coletados aleatoriamente, os resultados podem **não representar **a população.

Fonte: https://support.minitab.com/pt-br/minitab/18/help-and-how-to/graphs/how-to/histogram/before-you-start/data-considerations/

O Exemplo a seguir utiliza dados de sobre **expectativa de vidas do Brasil, Bolívia e EUA**. Os dados são relativos aos anos de 1960 a 2013 e possui a média em anos de expectativa de vida por país.

O arquivo origininal pode ser obtido em: https://www.kaggle.com/kumarajarshi/life-expectancy-who/data

**Formas de distribuição de um Histograma**

**Distribuição normal ou simétrica (curva de sino / Bell Curve)**

Os dados possuem variações pequenas. O pico dos dados fica ao centro do gráfico, e suas variações vão decrescendo de maneira simétrica dos dois lados;

![](https://github.com/paulosrl/imagens/blob/master/histogramanormal.png?raw=true)

**Histograma assimétrico**

O pico do histograma é concentrado em um dos lados (espalhado a esquerda ou a direita), e os dados fora de padrão decrescem para o lado oposto;

**Espalhado a esquerda**

![](https://github.com/paulosrl/imagens/blob/master/histo-esquerda.png?raw=true)

**Espalhado a direita**

![](https://github.com/paulosrl/imagens/blob/master/histo-direita.png?raw=true)

**Análise de Histogramas**

**Estudo de caso: Análise de histograma por uma coluna de dados**

No exemplo a seguir foi utilizado o mesmo banco de dados utilizado no exemplo dos boxplots. O banco de dados que armazena a expectativa de vida, dos Brasileiros, Bolivianos e Norte Americanos (em anos), no período de 1960 a 2013. Nos três gráficos a seguir (Histogramas) é possível observar a distribuição dos dados para os três países.
"""

#Brasil
vExpectativaBrasil = [54.69214634,55.16963415,55.63309756,56.08,56.51029268,56.92387805,57.32319512,57.7117561,58.09460976,58.47529268,58.85697561,59.24436585,59.63753659,60.0355122,60.43819512,60.83978049,61.23543902,61.62039024,61.9925122,62.35382927,62.70604878,63.05646341,63.4104878,63.77392683,64.14792683,64.53253659,64.92614634,65.32353659,65.72207317,66.11921951,66.515,66.90997561,67.30573171,67.70080488,68.09465854,68.48273171,68.86195122,69.23121951,69.58746341,69.92968293,70.25739024,70.56965854,70.86956098,71.15960976,71.44178049,71.71853659,71.99178049,72.26290244,72.53387805,72.80417073,73.07531707,73.34736585,73.61787805,73.88595122]
fig, ax = plt.subplots(1, 1, figsize=(10, 10))
fig.set_facecolor("white") # cor de fundo
plt.hist(vExpectativaBrasil,edgecolor='k')
#parâmetros do gráfico
vTitulo='Análise de Expectativa de Vida de 1960 a 2013'
vRotuloY='Frequencia de Idades'
vRotuloX='Idade'

#exibição do gráfico
ax.set_title(vTitulo)
ax.set_ylabel(vRotuloY)
ax.set_xlabel(vRotuloX)

plt.show()

#Bolivia
vExpectativaVidaBolivia = [42.66812195,42.97687805,43.28914634,43.60341463,43.92117073,44.23641463,44.54312195,44.84078049,45.13641463,45.43956098,45.76626829,46.13563415,46.56017073,47.05041463,47.60787805,48.23297561,48.92019512,49.65292683,50.41363415,51.18980488,51.96843902,52.74312195,53.50836585,54.26021951,54.98965854,55.69212195,56.36504878,57.01036585,57.6295122,58.21943902,58.77858537,59.30241463,59.79297561,60.25178049,60.68290244,61.09087805,61.48029268,61.85721951,62.22621951,62.59182927,62.95460976,63.31553659,63.67160976,64.02026829,64.3635122,64.70078049,65.03309756,65.36190244,65.68570732,66.00546341,66.31970732,66.62692683,66.92663415,67.21736585]
fig, ax = plt.subplots(1, 1, figsize=(10, 10))

fig.set_facecolor("white") # cor de fundo
plt.hist(vExpectativaVidaBolivia,edgecolor='k')

#parâmetros do gráfico
vTitulo='Análise de Expectativa de Vida de 1960 a 2013'
vRotuloY='Frequencia de Idades'
vRotuloX='Idade'


#exibição do gráfico
ax.set_title(vTitulo)
ax.set_ylabel(vRotuloY)
ax.set_xlabel(vRotuloX)

plt.show()

#EUA
vExpectativaVidaEUA = [69.77073171,70.27073171,70.1195122,69.91707317,70.16585366,70.21463415,70.21219512,70.56097561,69.95121951,70.50731707,70.80731707,71.10731707,71.15609756,71.35609756,71.95609756,72.60487805,72.85609756,73.25609756,73.35609756,73.80487805,73.65853659,74.00731707,74.36097561,74.46341463,74.56341463,74.56341463,74.61463415,74.76585366,74.76585366,75.01707317,75.21463415,75.36585366,75.64219512,75.4195122,75.57439024,75.62195122,75.99658537,76.42926829,76.5804878,76.58292683,76.63658537,76.73658537,76.83658537,76.98780488,77.33902439,77.33902439,77.58780488,77.83902439,77.93902439,78.0902439,78.54146341,78.64146341,78.74146341,78.84146341]
fig, ax = plt.subplots(1, 1, figsize=(10, 10))

fig.set_facecolor("white") # cor de fundo
plt.hist(vExpectativaVidaEUA,edgecolor='k')

#parâmetros do gráfico
vTitulo='Análise de Expectativa de Vida de 1960 a 2013'
vRotuloY='Frequencia de Idades'
vRotuloX='Idade'


#exibição do gráfico
ax.set_title(vTitulo)
ax.set_ylabel(vRotuloY)
ax.set_xlabel(vRotuloX)

plt.show()

"""**Estudo de caso: Análise de histogramas comparando três colunas de dados (países)**

Neste gráfico será feita uma superposição dos histogramas, ou seja, será possível comparar os três países em um único gráfico de histograma. O Brasil estrá na cor verde, Bolívia na cor amarela e EUA na cor azul.
"""

# Comparação dos 3 histogramas
vExpectativaVidaBrasil = [54.69214634,55.16963415,55.63309756,56.08,56.51029268,56.92387805,57.32319512,57.7117561,58.09460976,58.47529268,58.85697561,59.24436585,59.63753659,60.0355122,60.43819512,60.83978049,61.23543902,61.62039024,61.9925122,62.35382927,62.70604878,63.05646341,63.4104878,63.77392683,64.14792683,64.53253659,64.92614634,65.32353659,65.72207317,66.11921951,66.515,66.90997561,67.30573171,67.70080488,68.09465854,68.48273171,68.86195122,69.23121951,69.58746341,69.92968293,70.25739024,70.56965854,70.86956098,71.15960976,71.44178049,71.71853659,71.99178049,72.26290244,72.53387805,72.80417073,73.07531707,73.34736585,73.61787805,73.88595122]
vExpectativaVidaBolivia = [42.66812195,42.97687805,43.28914634,43.60341463,43.92117073,44.23641463,44.54312195,44.84078049,45.13641463,45.43956098,45.76626829,46.13563415,46.56017073,47.05041463,47.60787805,48.23297561,48.92019512,49.65292683,50.41363415,51.18980488,51.96843902,52.74312195,53.50836585,54.26021951,54.98965854,55.69212195,56.36504878,57.01036585,57.6295122,58.21943902,58.77858537,59.30241463,59.79297561,60.25178049,60.68290244,61.09087805,61.48029268,61.85721951,62.22621951,62.59182927,62.95460976,63.31553659,63.67160976,64.02026829,64.3635122,64.70078049,65.03309756,65.36190244,65.68570732,66.00546341,66.31970732,66.62692683,66.92663415,67.21736585]
vExpectativaVidaEUA = [69.77073171,70.27073171,70.1195122,69.91707317,70.16585366,70.21463415,70.21219512,70.56097561,69.95121951,70.50731707,70.80731707,71.10731707,71.15609756,71.35609756,71.95609756,72.60487805,72.85609756,73.25609756,73.35609756,73.80487805,73.65853659,74.00731707,74.36097561,74.46341463,74.56341463,74.56341463,74.61463415,74.76585366,74.76585366,75.01707317,75.21463415,75.36585366,75.64219512,75.4195122,75.57439024,75.62195122,75.99658537,76.42926829,76.5804878,76.58292683,76.63658537,76.73658537,76.83658537,76.98780488,77.33902439,77.33902439,77.58780488,77.83902439,77.93902439,78.0902439,78.54146341,78.64146341,78.74146341,78.84146341]
#dados = {'Brasil': vEexpectativaVidaBrasil, 'Bolivia': vEexpectativaVidaBolivia,'EUA':vEexpectativaVidaEUA}
#df = pd.DataFrame(data=dados)

plt.figure(figsize=(15, 10))

plt.title('Brasil X Bolívia X EUA - Distribuição da expectativa de vida de 1960 a 2013')
plt.xlabel('Média de Idade')
plt.ylabel('Frequência por Idade')

plt.hist(vExpectativaVidaBrasil, 
         alpha=0.4, label='Brasil', color='#86E283')
plt.hist(vExpectativaVidaBolivia, 
         alpha=0.4, label='Bolivia', color='#FBFF65')
plt.hist(vExpectativaVidaEUA, 
         alpha=0.4, label='EUA', color='#65A8FF')

plt.legend();

"""### **Estudos de caso (Boxplot x Histogramas na Análise Exploratória de dados)**

Os dados a seguir mostram três tipos de situações, **dados pouco dispersos, dados muito dispersos e dados com uma distribuição normal**. 

O Exemplo a seguir contém os dados de três sites (site1, site2 e site3), cada valor representa o número de acessos que os respectivos sites tiveram em um dia, foram coletados os dados de 60 dias.

Para cada site, será plotado um histograma e um boxplot.
"""

# dados com números de acessos a três sites, cada valor representa o número de acessos por dia
site1=[57 , 55 , 90 , 76 , 58 , 73 , 75 , 71 , 45 , 65 , 80 , 79 , 65 , 78 , 66 , 58 , 57 , 67 , 54 , 71 , 56 , 69 , 64 , 86 , 66 , 71 , 75 , 77 , 81 , 83 , 74 , 75 , 65 , 75 , 66 , 74 , 67 , 54 , 67 , 83 , 79 , 61 , 75 , 63 , 78 , 75 , 73 , 98 , 81 , 80 , 80 , 76 , 70 , 68 , 62 , 46 , 72 , 71 , 85 , 70] 
site2=[45 , 10 , 90 , 76 , 46 , 73 , 20 , 71 , 45 , 65 , 80 , 79 , 97 , 78 , 66 , 60 , 50 , 98 , 50 , 30 , 45 , 69 , 64 , 86 , 70 , 51 , 75 , 77 , 45 , 83 , 85 , 98 , 52 , 20 , 27 , 88 , 49 , 99 , 92 , 83 , 79 , 68 , 99 , 68 , 94 , 80 , 45 , 98 , 88 , 95 , 99 , 76 , 70 , 67 , 93 , 55 , 95 , 92 , 98 , 6] 
site3=[10 , 10 , 10 , 76 , 12 , 73 , 20 , 9 , 45 , 55 , 9 , 79 , 97 , 78 , 8 , 60 , 5 , 33 , 50 , 30 , 45 , 59 , 7 , 86 , 70 , 12 , 75 , 7 , 25 , 37 , 35 , 37 , 25 , 20 , 27 , 88 , 49 , 4 , 80 , 7 , 28 , 59 , 27 , 68 , 23 , 3 , 45 , 29 , 34 , 35 , 24 , 60 , 50 , 59 , 25 , 55 , 95 , 34 , 35 , 6]

# Analisando os dados do Site 1
# podemos perceber que a média está muito próxima da mediana o que 
# sugere um desvio padrão baixo e uma distribuição normal dos dados.
site = site1
a=pd.Series(site).mean()
b=pd.Series(site).median()
c=pd.Series(site).std()
print('Media = ',a)
print('Mediana = ',b)
print('Desvio Padrão = ',c)

# Histograma do Site 1 
# Espera-se o distribuição simétrica dos dados
s=site1
fig, ax = plt.subplots(figsize=(8, 8))
fig.set_facecolor("white") # cor de fundo
plt.hist(s, bins=7, edgecolor='k');

# Boxplot do Site 1 
# Espera-se o distribuição simétrica dos dados
s=site1
fig, ax = plt.subplots(figsize=(8,8))
fig.set_facecolor("white") # cor de fundo
ax.boxplot(s);

# Analisando os dados do Site 2
# podemos perceber que a média se afasta da mediana o que 
# sugere um maior desvio padrão baixo e uma 
# distribuição mais espalhada dos dados.
site = site2
a=pd.Series(site).mean()
b=pd.Series(site).median()
c=pd.Series(site).std()
print('Media = ',a)
print('Mediana = ',b)
print('Desvio Padrão = ',c)

# Histograma do Site 2 
# histograma com espalhamento a esquerda
s=site2
fig, ax = plt.subplots(figsize=(10, 10))
fig.set_facecolor("white") # cor de fundo
plt.hist(s, bins=7,edgecolor='k');

# Boxplot do Site 2 
# Espera-se o distribuição com espalhamento dos dados
# os dados devem tender para os maiores valores em função do 
# que foi observado no histograma 
s=site2
fig, ax = plt.subplots(figsize=(10,10))
fig.set_facecolor("white") # cor de fundo
ax.boxplot(s);

# Analisando os dados do Site 3
# podemos perceber que a média se afasta da mediana o que 
# sugere um maior desvio padrão baixo e uma 
# distribuição mais espalhada dos dados.
site = site3
a=pd.Series(site).mean()
b=pd.Series(site).median()
c=pd.Series(site).std()
print('Media = ',a)
print('Mediana = ',b)
print('Desvio Padrão = ',c)

# Histograma do Site 3 
# histograma com espalhamento a direita
s=site3
fig, ax = plt.subplots(figsize=(10, 10))
fig.set_facecolor("white") # cor de fundo
plt.hist(s, bins=7,edgecolor='k');

# Boxplot do Site 3 
# Espera-se o distribuição com espalhamento dos dados
# os dados devem tender para os menores valores em função do 
# que foi observado no histograma 
s=site3
fig, ax = plt.subplots(figsize=(10,10))
fig.set_facecolor("white") # cor de fundo
ax.boxplot(s);

plt.figure(figsize=(20, 12))
plt.title('Site1 X Site2 X Site3')
plt.xlabel('Acessos')
plt.ylabel('Frequência de Acessos')

plt.hist(site1, 
         label='site1', alpha=0.4,color='#86E283',bins=7)
plt.hist(site2, 
         label='site2', alpha=0.4,color='#FBFF65',bins=7)
plt.hist(site3, 
         label='site3', alpha=0.4, color='#65A8FF',bins=7)

plt.legend();

"""A forma da distribuição dos dados pode ser analisada por meio do diagrama em caixas de acordo com a figura a seguir, a distribuição amostral pode ser comparada com a distribuição também observada nos histogramas.

![](https://raw.githubusercontent.com/paulosrl/imagens/master/Histogramas.jpg)

##**06. Coeficiente de Correlação de Pearson**

Em muitas análises de dados deseja-se analisar a **relação entre duas medidas quantitativas**. Uma das grandes contribuições da estatística para ampliar o entendimento humano sobre os fenômenos observados é a capacidade de **medir a relação entre diferentes variáveis**. Os coeficientes de correlação auxiliam os pesquisadores a **mensurar** essa relação.

A correlação busca  **entender como uma variável se comporta em relação a outra variável**, buscando identificar se existe alguma relação entre a variabilidade de ambas. Correlação **não implique em causalidade**, ou seja, duas variáveis correlacionadas não implicam, necessariamente, no fato de uma ser causa da outra.

**Exemplo:** 

* Analisar a quantidade de sorvetes vendidos relacionados a **temperatura em dias de calor acentuado**. Observa-se que a quantidade de sorvetes vendidos **aumenta**. Esta relação é chamada de **correlação positiva** entre temperaturas e quantidade de sorvetes vendidos;

* **Não é possível afirmar** que se forem vendidos mais sorvetes a temperatura do dia ficará aumentará, ou seja, não é possível afirmar que a **causa do calor** seja o **aumento das vendas**. Daí a afirmação que **correlação NÃO implica em causalidade**.

####**Tipos de Correlação**

* **Correlação positiva:** Esse tipo acontece quando há uma tendência crescente entre os pontos, ou seja, conforme uma variável aumenta, a outra aumenta proporcionalmente;
* **Correlação negativa:** Aqui, a correlação se faz em uma linha decrescente. Enquanto uma variável aumenta, a outra diminui de forma proporcional;
* **Correlação forte:** Quanto menor for a dispersão dos pontos, maior será a correlação dos dados. Com isso, a correlação forte se dá quando os dados estão altamente concentrados;
* **Correlação fraca:** Seguindo a mesma linha da correlação anterior, quanto mais distantes estão os pontos, mais fraca é a correlação.

![](https://github.com/paulosrl/imagens/blob/master/correlacao.png?raw=true)

####**Calculo do coeficiente de Correlação**

* Mede a força da correlação e a direção dessa correlação (positiva, negativa, linear ou espalhada) entre duas variáveis, normalmente representado pela letra **r**;

* Assume apenas valores entre -1 e 1;

* **r = 1** : correlação perfeita positiva (direta) entre as duas variáveis;

* **r = -1** : correlação negativa (indireta) perfeita entre as duas variáveis, ou seja, se uma aumenta, a outra sempre diminui;

* **r = 0 :** as duas variáveis não dependem linearmente uma da outra. Porém, pode existir uma dependência não linear. Assim, o resultado deve ser investigado por outros meios.

**Força da relação (r)**

* 0.7 ≤ **r** ≤ 1.0: (+/-) **correlação forte**;
* 0.3 ≤ **r** < 0.7: (+/-) **correlação moderada**;
* 0.0 ≤ **r** < 0.3: (+/-) **correlação fraca**;

**Exemplos:**

![](https://github.com/paulosrl/imagens/blob/master/Pearson.png?raw=true)

Fonte do gráfico : https://statistics.laerd.com/statistical-guides/pearson-correlation-coefficient-statistical-guide.php

####**Estudos de caso (Coeficientes de Correlação)**

**01. Foram coletados os dados de horas de estudo e as notas obtidas por um grupo de alunos. Qual a correlação entre essas variávies?**
"""

#matriz com os dados de horas de estudo
horasEstudo=[20,12,14,15,18,9,5,4,8,13,14,15,19,18,12,11,10,15,17,20]
#matriz com os dados notas
Notas=[9.5,2.5,3.6,6.7,5.2,1,0,1.5,2,3,3.5,4.5,8.5,7.5,5,4,3,5,6.5,10]

#### gráfico
plt.figure(figsize=(12, 8))
plt.title('Correlação entre horas de estudo e notas')
plt.xlabel('Horas de Estudo')
plt.ylabel('Notas')
#correlação que será analisada
plt.scatter(horasEstudo, Notas)
plt.show()

"""**02. Foram coletados dados refentes a dias com gelo e temperatura média de vários anos. Qual a correlação entre essas duas variáveis?**"""

#variáveis ou colunas que serão analisadas
TemperaturaMedia=[22.94,23.02,25.68,19.96,24.80,23.98,22.10,20.30,24.20,22.74,24.16,24.94,22.40,22.14,20.84,25.66,21.73,24.49,24.13,22.17,21.73,20.41,24.41,23.95,20.95,26.71,22.81,23.11,23.33,28.83,23.11,21.47,23.97,24.75,23.61,23.08,21.24,26.63,23.88]
DiascomGelo=[87,137,106,97,105,118,118,136,91,107,96,114,125,115,118,82,115,97,104,146,126,141,111,123,118,83,48,118,116,81,116,123,112,99,102,118,63,62,132]
Titulo='Correlação entre Temperatura Média e dias com Gelo'
EixoX='Temperatura média'
EixoY='Dias com gelo'
#configurar gráfico
x=TemperaturaMedia
y=DiascomGelo
#### gráfico
plt.figure(figsize=(12, 8))
plt.title(Titulo)
plt.xlabel(EixoX)
plt.ylabel(EixoY)
#correlação que será analisada
plt.scatter(x, y)
plt.show()

"""**03. Foram coletados dados refentes a largura e comprimento de um determinado molusco. Qual a correlação entre essas duas variáveis?**

"""

#variáveis ou colunas que serão analisadas
larguraCM=[1.3,1.4,1.4,1.5,1.9,2.1,2.1,2.1,2.2,2.2,2.3,2.4,2.4,2.5,2.5,2.6,2.6,2.6,2.7,2.8,2.8,2.9,2.9,2.9,2.9,3.0,3.0,3.0,3.1,3.4,3.4,3.5,3.6,3.6,3.6,3.6,3.7,3.9,3.9,4.1,4.1,4.1,4.2,4.2,4.2,4.2,4.3,4.7,4.8,4.8,4.8,4.9,5.0,5.0,5.1,5.2,5.2,5.4,5.6,5.6,5.8,5.8,5.8,5.9,6.0,6.0,6.0,6.2,6.2,6.3,6.5,6.6,6.6,6.7,6.7,6.7,6.7,6.9,6.9,7.0,7.1,7.1,7.1,7.2,7.3,7.3,7.4,7.5]
comprimentoCM=[1.7,1.9,1.8,1.9,2.3,3.5,2.8,2.7,3.0,2.7,3.0,3.2,2.9,3.5,3.3,3.5,3.4,3.4,3.2,3.8,3.5,3.8,3.9,3.8,3.7,3.8,4.0,3.7,4.1,4.4,4.3,4.5,4.6,4.8,4.9,4.5,4.9,5.4,5.2,5.3,5.4,5.2,5.4,5.5,5.6,5.2,5.6,6.1,6.6,6.1,6.0,6.1,6.6,6.2,6.6,6.4,6.8,6.3,7.0,7.9,7.4,7.4,6.9,7.9,7.7,7.8,7.3,8.5,7.5,7.6,9.3,8.1,8.0,8.2,9.2,8.0,7.9,8.6,8.1,9.5,9.1,9.1,9.4,8.4,9.3,8.9,8.9,8.6]
Titulo='Correlação entre comprimento e largura dos moluscos'
EixoX='Largura em cm'
EixoY='Comprimento em cm'
#configurar gráfico
x=larguraCM
y=comprimentoCM
#### gráfico
plt.figure(figsize=(12, 8))
plt.title(Titulo)
plt.xlabel(EixoX)
plt.ylabel(EixoY)
#correlação que será analisada
plt.scatter(x, y)
plt.show()